// ... existing imports ...
class DevOrchestrator:
    # ... existing code ...
    def _attempt_rollback(self):
        # ... existing code before rollback ...
        self.shell.git_reset_hard("HEAD")
        # ... rest of method ...
    # ... rest of class ...
